SCREEN_HEIGHT = 900
SCREEN_WIDTH = 600
PLAYING_AREA_X = 500
PLAYING_AREA_Y = 800
GRID_SIZE = 30
SNEAK_HEAD_SIZE_X = 50
SNEAK_HEAD_SIZE_Y = 45
HAPPY_SNEAK_HEAD_SIZE_X = 52
HAPPY_SNEAK_HEAD_SIZE_Y = 50
SNEAK_BODY_SIZE = 45
LAWN_MOWER_SIZE_X = 100
LAWN_MOWER_SIZE_Y = 175
FRUIT_SIZE = 42
MOVEMENT_SPEED = GRID_SIZE
LAWN_MOWER_COOLDOWN = 150
LAWN_MOWER_WARNING_SIZE = 75
GAME_SPEED = 13
BUSH_IMAGE = "assets/bush_asset.png"
LAWN_MOWER_IMAGE = "assets/lawn_mower.png"
LAWN_MOWER_WARNING_IMAGE = "assets/lawn_warning.png"
BACKGROUND_COLOR = (193, 225, 54)
SNAKE_COLOR = (141, 199, 63)
FRUIT_IMAGE_ARRAY = ["assets/redapple.png", "assets/cherries.png", "assets/blueberry.png", "assets/banana.png"]
SNAKE_IMAGE_ARRAY = ["assets/snake_head_up.png", "assets/snake_head_up_out.png"]
SNAKE_BODY_IMAGE = "assets/snake_body.png"
SCORE_FONT = "freesansbold.ttf"
DIRECTORY = "assets/"